repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/pycqa/flake8
    rev: "6.0.0" # pick a git hash / tag to point to
    hooks:
      - id: flake8
  - repo: https://github.com/hmrc/security-git-hooks
    rev: release/1.9.0
    hooks:
      - id: secrets_filecontent
        name: Checking staged files for sensitive content
        exclude: >-
          .tar$|.gz$|.jar$|.7z$|.rar$|.bz2$|.zip$|.gzip$|.war$|.ear$|.xlsx$
          |.xls$|.docx$|.doc$|.pptx$|.pdf$|.jpg$|.png$|.jpeg$|.tif$|.tiff$
          |.gif$|.bmp$|.webp$|.svg$|.ico$|.psd$|.exe$|.dll$|.dmg$|.de$|.rpm$|
      - id: secrets_filename
        name: Checking staged files for sensitive file types
        exclude: >-
          .tar$|.gz$|.jar$|.7z$|.rar$|.bz2$|.zip$|.gzip$|.war$|.ear$|.xlsx$
          |.xls$|.docx$|.doc$|.pptx$|.pdf$|.jpg$|.png$|.jpeg$|.tif$|.tiff$
          |.gif$|.bmp$|.webp$|.svg$|.ico$|.psd$|.exe$|.dll$|.dmg$|.de$|.rpm$|
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: ^.*\.py$
      - id: end-of-file-fixer
        exclude: ^.*\.py$
      - id: check-merge-conflict
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.9-for-vscode"
    hooks:
      - id: prettier
        exclude: ^.*\.py$
  - repo: https://github.com/mrtazz/checkmake
    rev: 0.2.2
    hooks:
      - id: checkmake
        files: Makefile
