version: "3.9"

services:
  postgres-test:
    image: postgres:15
    ports:
      - "65444:5432"
    env_file:
      - .env.test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
